#define utils_implementation
#include <utils/MS/window/hwnd_wrapper.h>
#include <utils/MS/window/window.h>
#include <utils/MS/window/style.h>
#include <utils/MS/window/regions.h>
#include <utils/MS/window/snap_on_drag.h>
#include <utils/MS/window/taskbar.h>
#include <utils/MS/window/input/keyboard.h>
#include <utils/MS/window/input/mouse.h>
#include <utils/MS/window/input/passthrough.h>
#include <utils/MS/window/details/style.h>
#include <utils/MS/error_to_exception.h>